/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出 run */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** 创建新 run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** run 详情 */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        /** 关闭并移除 run（v0.2：从 registry 卸载） */
        delete: operations["delete_run_api_v1_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 推进一 tick */
        post: operations["step_run_api_v1_runs__run_id__step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 暂停 */
        post: operations["pause_run_api_v1_runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复 */
        post: operations["resume_run_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前 WorldState */
        get: operations["get_state_api_v1_runs__run_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已存的 tick 列表 */
        get: operations["list_snapshots_api_v1_runs__run_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/snapshots/{tick}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定 tick 的 Snapshot */
        get: operations["get_snapshot_api_v1_runs__run_id__snapshots__tick__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 事件查询（分页 + 过滤） */
        get: operations["query_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/intervene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 应用人工干预 */
        post: operations["intervene_api_v1_runs__run_id__intervene_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分析报告（含可选 LLM 增强） */
        get: operations["get_analysis_api_v1_runs__run_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 显式重新生成分析报告 */
        post: operations["post_analyze_api_v1_runs__run_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出可用场景（场景画廊数据源）
         * @description 扫描 ``scenarios/`` 目录返画廊数据。
         *
         *     实现策略：
         *     - 扫描 `<scenarios_root>/*\/scenario.yaml`
         *     - 用 PyYAML 直读（不走 scenario_loader——避免对 world.yaml 的强依赖）
         *     - 失败的场景文件**跳过**（容忍 yaml 语法错），但记录在 server 日志里
         *     - 返回 `ScenarioSummary` 列表，按 id 字典序排序
         *
         *     `scenarios_root` 由 `app.state.scenarios_root` 配置，默认 `<cwd>/scenarios/`。
         */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 + 活跃 run 数 */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionEffectSchema
         * @description 动作效果类型定义。
         */
        ActionEffectSchema: {
            /**
             * Kind
             * @description 效果类别
             * @enum {string}
             */
            kind: "self_attribute" | "relation" | "message" | "environment";
        };
        /**
         * ActionParamSchema
         * @description 动作参数定义（D-014 扩充版）。
         *
         *     除 ``type`` / ``required`` 外，其余字段均为可选——向后兼容现有 YAML。
         *
         *     跨字段约束（由 ``_check_param_constraints`` 实施）：
         *
         *     1. ``default`` 非 None 时，类型必须与 ``type`` 一致（number↔int/float、
         *        string↔str、boolean↔bool、entity_ref↔str）；注意 ``bool`` 是 ``int`` 的
         *        子类，number 校验必须显式排除 bool
         *     2. ``min`` / ``max`` 仅在 ``type="number"`` 时有意义
         *     3. ``values`` 仅在 ``type="string"`` 时有意义
         *     4. ``entity_type_filter`` 仅在 ``type="entity_ref"`` 时有意义
         *     5. ``min <= max``（若两者都给）
         *     6. ``default in values``（若 ``values`` 给了）
         *
         *     JSON Schema 不强制 cross-field 约束（按项目惯例双层分工：JSON Schema 做语
         *     法层、Pydantic 做语义层），约束 2-6 仅在本层强制。
         */
        ActionParamSchema: {
            /**
             * Type
             * @description 参数类型
             * @enum {string}
             */
            type: "number" | "string" | "boolean" | "entity_ref";
            /**
             * Required
             * @description 是否必填
             * @default false
             */
            required: boolean;
            /**
             * Description
             * @description 参数语义说明，LLM/前端读取
             */
            description?: string | null;
            /**
             * Default
             * @description 默认值，required=False 时降级 + random mode 填值
             */
            default?: unknown;
            /**
             * Min
             * @description 数值下限（type=number 时）
             */
            min?: number | null;
            /**
             * Max
             * @description 数值上限（type=number 时）
             */
            max?: number | null;
            /**
             * Values
             * @description 枚举候选值（type=string 时）
             */
            values?: string[] | null;
            /**
             * Entity Type Filter
             * @description 实体类型限定（type=entity_ref 时）
             */
            entity_type_filter?: string[] | null;
        };
        /**
         * ActionTypeSchema
         * @description 动作类型模板。
         */
        ActionTypeSchema: {
            /**
             * Description
             * @description 动作描述
             */
            description?: string | null;
            /**
             * Actor Types
             * @description 允许执行该动作的实体类型列表
             */
            actor_types: string[];
            /**
             * Params
             * @description 动作参数定义
             */
            params: {
                [key: string]: components["schemas"]["ActionParamSchema"];
            };
            /**
             * Effects
             * @description 动作效果类型列表
             */
            effects: components["schemas"]["ActionEffectSchema"][];
        };
        /**
         * ActivationAttributeTrigger
         * @description 实体属性触发条件。
         */
        ActivationAttributeTrigger: {
            /**
             * Field
             * @description 实体属性字段名
             */
            field: string;
            /**
             * Gte
             * @description 属性值大于等于阈值时触发
             */
            gte?: number | null;
            /**
             * Lte
             * @description 属性值小于等于阈值时触发
             */
            lte?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ActivationEnvironmentTrigger
         * @description 环境变化触发条件。
         */
        ActivationEnvironmentTrigger: {
            /**
             * Field
             * @description 环境变量字段名
             */
            field: string;
            /**
             * Gte Delta
             * @description 变化量大于等于阈值时触发
             */
            gte_delta?: number | null;
            /**
             * Lte Delta
             * @description 变化量小于等于阈值时触发
             */
            lte_delta?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ActivationSchema
         * @description 实体激活策略。
         *
         *     Runtime 会读取这里的配置来决定某个实体在当前 tick 是否进入决策流程。
         */
        ActivationSchema: {
            /**
             * On Message
             * @description 收到消息时是否激活
             * @default true
             */
            on_message: boolean;
            /**
             * Decision Interval
             * @description 最短决策间隔，单位为 tick
             * @default 1
             */
            decision_interval: number;
            /**
             * Wake On
             * @description 关键事件触发器
             */
            wake_on?: ("environment_changed" | "relation_changed" | "action_finished")[] | null;
            /**
             * Environment Triggers
             * @description 环境变量变化触发条件
             */
            environment_triggers?: components["schemas"]["ActivationEnvironmentTrigger"][] | null;
            /**
             * Attribute Triggers
             * @description 实体属性触发条件
             */
            attribute_triggers?: components["schemas"]["ActivationAttributeTrigger"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ActorStat
         * @description 按 `actor_id` 的行为统计条目。
         *
         *     只统计两类有业务含义的事件：
         *     - `action_executed`——真正落地的动作
         *     - `decision_rejected`——被规则层拒绝的决策提议
         *     其他事件（如 `decision_proposed`）每次都会写，信噪比低，不计入。
         */
        ActorStat: {
            /**
             * Actor Id
             * @description 实体 id
             */
            actor_id: string;
            /**
             * Action Count
             * @description action_executed 事件数
             */
            action_count: number;
            /**
             * Decision Rejected Count
             * @description decision_rejected 事件数
             */
            decision_rejected_count: number;
        };
        /**
         * AnalysisConfig
         * @description 分析相关配置。
         *
         *     第一版只定义"需要保留哪些字段"，不定义"如何分析"。
         *     分析算法本身属于分析层，不属于场景配置。
         */
        AnalysisConfig: {
            /**
             * Snapshot Fields
             * @description 需要保留的快照字段集合（可选）
             */
            snapshot_fields?: ("entities" | "relations" | "environment" | "messages")[] | null;
        };
        /**
         * AnalysisResult
         * @description 分析层的顶层产物——一次 `analyze_run` 调用的完整结果。
         *
         *     **分层**（session 26 LLM 增强升级后）：
         *     - 前六个字段是 Phase A 纯规则核心填——100% 确定性：
         *       ``version`` / ``run_id`` / ``summary`` / ``turning_points`` /
         *       ``entity_comparisons`` / ``environment_trajectory``
         *     - 后四个字段是 Phase C LLM 增强层填；Phase A 默认 None：
         *       ``world_overview`` / ``narrative_summary`` / ``situation_judgement`` /
         *       ``next_action_suggestions``
         *     - 渲染 markdown 时 Phase A 产物总有，LLM 增强段发现 None 会省略对应 section
         */
        AnalysisResult: {
            /**
             * Version
             * @description AnalysisResult schema 版本号
             * @default 0.1
             * @constant
             */
            version: "0.1";
            /**
             * Run Id
             * @description 对应的 run_id
             */
            run_id: string;
            /** @description 全轨迹总览（对应 MVP 10.3 #1） */
            summary: components["schemas"]["TrajectorySummary"];
            /**
             * Turning Points
             * @description 关键转折点列表（对应 MVP 10.3 #2），按 |delta| 降序
             */
            turning_points?: components["schemas"]["TurningPoint"][];
            /**
             * Entity Comparisons
             * @description 各实体初态 vs 终态对比（对应 MVP 10.3 #3）
             */
            entity_comparisons?: components["schemas"]["EntityComparison"][];
            /**
             * Environment Trajectory
             * @description 环境变量轨迹；未变化变量保留单点初态
             */
            environment_trajectory?: components["schemas"]["EnvironmentChange"][];
            /**
             * World Overview
             * @description LLM 生成的世界概览（Phase C 填）：用自然语言解释本次仿真的初始世界——包含哪些实体、各自的角色与初始属性含义、实体间关系含义、场景目标。为不熟悉 world.yaml / scenario.yaml 的读者提供背景。
             */
            world_overview?: string | null;
            /**
             * Narrative Summary
             * @description LLM 生成的自然语言总览（Phase C 填；对应 MVP 10.3 #4 前半）。应援引具体 tick / 属性变化作证据。
             */
            narrative_summary?: string | null;
            /**
             * Situation Judgement
             * @description LLM 生成的局势判断（Phase C 填；对应 MVP 10.3 #4 后半）。应援引 turning_points / entity_comparisons 中的具体数值变化作证据。
             */
            situation_judgement?: string | null;
            /**
             * Next Action Suggestions
             * @description LLM 生成的面向用户建议条目（Phase C 填；对应 MVP 10.3 #5）。每条应在文本内嵌入支撑证据（具体 tick / 数值 / 实体）。
             */
            next_action_suggestions?: string[] | null;
        };
        /**
         * AnalyzeRequest
         * @description 显式触发分析的请求体（POST /api/v1/runs/:id/analyze）。
         *
         *     与 GET /analysis 的差别：POST 表达"重新生成"语义——前端"重跑增强"按钮调它。
         */
        AnalyzeRequest: {
            /**
             * Llm Enhance
             * @description 是否触发 Phase C LLM 增强（4 段叙事报告）
             * @default false
             */
            llm_enhance: boolean;
        };
        /**
         * AttributeChange
         * @description 实体某属性从 `before` 变到 `after` 的单条记录。
         *
         *     用于 `EntityComparison.changes`——只收录实际变化过的属性；未变化的
         *     属性不进此列表（避免渲染时噪声）。
         *
         *     - `before is None`：该属性在 initial snapshot 中**不存在**（实体中途新增或
         *       v1 不会出现，保留 Nullable 以兼容未来）
         *     - `after` 永远非 None（因为 final snapshot 里有这条属性才会进这个列表）
         */
        AttributeChange: {
            /**
             * Attribute
             * @description 属性名
             */
            attribute: string;
            /**
             * Before
             * @description 初始值；None 表示属性在初始快照中缺失
             */
            before?: unknown;
            /**
             * After
             * @description 终态值
             */
            after: unknown;
        };
        /**
         * AttributeSchema
         * @description 属性模板定义。
         *
         *     用于描述实体属性或环境变量的类型、范围、默认值等静态约束。
         */
        AttributeSchema: {
            /**
             * Type
             * @description 属性类型
             * @enum {string}
             */
            type: "number" | "string" | "boolean" | "enum" | "entity_ref";
            /**
             * Min
             * @description 数值最小值（可选）
             */
            min?: number | null;
            /**
             * Max
             * @description 数值最大值（可选）
             */
            max?: number | null;
            /**
             * Default
             * @description 默认值
             */
            default?: unknown;
            /**
             * Values
             * @description 枚举候选值列表
             */
            values?: string[] | null;
            /**
             * Clamp
             * @description 是否自动截断到 min/max 范围
             * @default true
             */
            clamp: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * Breakpoint
         * @description 断点定义。
         */
        Breakpoint: {
            /**
             * Id
             * @description 断点唯一标识
             */
            id: string;
            /** @description 断点触发条件 */
            when: components["schemas"]["BreakpointWhen"];
        };
        /**
         * BreakpointEntityCondition
         * @description 针对某个实体某个属性的断点触发条件。
         */
        BreakpointEntityCondition: {
            /**
             * Id
             * @description 目标实体 id
             */
            id: string;
            /**
             * Attribute
             * @description 目标属性名
             */
            attribute: string;
            /**
             * Gte
             * @description 大于等于阈值时触发
             */
            gte?: number | null;
            /**
             * Lte
             * @description 小于等于阈值时触发
             */
            lte?: number | null;
        };
        /**
         * BreakpointEnvironmentCondition
         * @description 针对单个环境变量的断点触发条件。
         */
        BreakpointEnvironmentCondition: {
            /**
             * Gte
             * @description 大于等于阈值时触发
             */
            gte?: number | null;
            /**
             * Lte
             * @description 小于等于阈值时触发
             */
            lte?: number | null;
        };
        /**
         * BreakpointWhen
         * @description 断点触发条件容器。
         *
         *     第一版只支持简单条件组合，不支持复杂布尔表达式。
         *     `environment` 与 `entity` 至少配置一项才有意义，这条语义检查由 loader 负责。
         */
        BreakpointWhen: {
            /**
             * Environment
             * @description 按环境变量名映射到触发条件；未配置时视为空
             */
            environment?: {
                [key: string]: components["schemas"]["BreakpointEnvironmentCondition"];
            };
            /** @description 单个实体属性触发条件（可选） */
            entity?: components["schemas"]["BreakpointEntityCondition"] | null;
        };
        /**
         * CreateRunRequest
         * @description 创建 run 的请求体（POST /api/v1/runs）。
         *
         *     字段语义对齐 `cli/run.py cmd_run` 的命令行参数——v0.2 server 是 CLI 的网络化等价物。
         */
        CreateRunRequest: {
            /**
             * Scenario Path
             * @description scenario.yaml 相对仓库根的路径（或绝对路径）
             */
            scenario_path: string;
            /**
             * World Path
             * @description world.yaml 路径；默认 <scenario_dir>/world.yaml
             */
            world_path?: string | null;
            /** @description 可选 runtime 配置覆盖；省略时用模型默认值 */
            runtime_config?: components["schemas"]["RuntimeConfig"] | null;
            /**
             * Llm Provider
             * @description LLM provider 类型——v0.2 默认 mock 离线；openai 需配 provider_key
             * @default mock
             * @enum {string}
             */
            llm_provider: "mock" | "openai";
            /**
             * Provider Key
             * @description config/llm.yaml 的 providers 字典 key；省略时用 default_provider
             */
            provider_key?: string | null;
            /**
             * Config Llm Path
             * @description LLM 配置文件路径；默认 config/llm.yaml；仅 llm_provider=openai 用
             */
            config_llm_path?: string | null;
            /**
             * Ticks Override
             * @description 覆盖 scenario.config.total_ticks；省略走 scenario 声明
             */
            ticks_override?: number | null;
            /**
             * Run Id
             * @description 显式 run_id；None 时由 EventLog.generate_run_id 自动生成
             */
            run_id?: string | null;
        };
        /**
         * DefaultsSchema
         * @description 运行默认参数。
         *
         *     这些参数是世界级默认值，不等同于规则实现本身。
         */
        DefaultsSchema: {
            /**
             * Conflict Resolution
             * @description 默认冲突解决策略
             * @default both
             * @enum {string}
             */
            conflict_resolution: "both" | "priority" | "random";
            /**
             * Max Messages Per Tick
             * @description 单 tick 消息上限
             * @default 100
             */
            max_messages_per_tick: number;
            /**
             * Fallback Action
             * @description 决策失败时的降级动作
             */
            fallback_action?: string | null;
            /**
             * Action Effect Order
             * @description 动作效果的默认执行顺序
             */
            action_effect_order?: ("self_attribute" | "relation" | "environment" | "message")[];
        };
        /**
         * EntityComparison
         * @description 单个实体的初态与终态对比——对应 MVP 10.3 #3"各实体最终状态比较"。
         *
         *     - `initial_attributes` / `final_attributes` 是两份完整快照（所有属性）
         *     - `changes` 只列出实际变化的属性——渲染 markdown 时先看 `changes` 找重点，
         *       需要完整对比表时再走 `initial_/final_attributes`
         */
        EntityComparison: {
            /**
             * Entity Id
             * @description 实体 id
             */
            entity_id: string;
            /**
             * Initial Attributes
             * @description 初始 snapshot 的全部属性快照
             */
            initial_attributes?: {
                [key: string]: unknown;
            };
            /**
             * Final Attributes
             * @description 最终 snapshot 的全部属性快照
             */
            final_attributes?: {
                [key: string]: unknown;
            };
            /**
             * Changes
             * @description 实际变化的属性列表（空列表表示该实体整个仿真没变化）
             */
            changes?: components["schemas"]["AttributeChange"][];
        };
        /**
         * EntityInstance
         * @description 实体实例。
         */
        EntityInstance: {
            /**
             * Id
             * @description 实体唯一标识
             */
            id: string;
            /**
             * Type
             * @description 实体类型名，必须在 World Definition 中声明
             */
            type: string;
            /**
             * Name
             * @description 实体可读名称（可选）
             */
            name?: string | null;
            /**
             * Attributes
             * @description 实体实例属性覆盖值；未提供的属性由 loader 回填 World Definition 默认值
             */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /**
         * EntityRuntimeState
         * @description 单个实体在当前 tick 的运行时状态。
         *
         *     与 `models/scenario_models.EntityInstance` 的区别：
         *
         *     - EntityInstance 描述"场景文件里写的初始化覆盖值"，字段语义是 override
         *     - EntityRuntimeState 描述"跑到当前 tick 时该实体的全部当前属性值"，无 override 语义
         *     - 由 Runtime 初始化时从 World Definition 默认值 + Scenario 覆盖值合并生成
         */
        EntityRuntimeState: {
            /**
             * Id
             * @description 实体唯一标识
             */
            id: string;
            /**
             * Type
             * @description 实体类型名
             */
            type: string;
            /**
             * Name
             * @description 实体可读名称（可选）
             */
            name?: string | null;
            /**
             * Attributes
             * @description 当前属性值；键集合应与 World Definition.entity_types[type].attributes 对齐
             */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /**
         * EntityTypeSchema
         * @description 实体类型模板。
         */
        EntityTypeSchema: {
            /**
             * Description
             * @description 实体类型描述
             */
            description?: string | null;
            /**
             * Decision Mode
             * @description 决策模式
             * @enum {string}
             */
            decision_mode: "llm" | "rule" | "random";
            /** @description 激活策略 */
            activation?: components["schemas"]["ActivationSchema"] | null;
            /** @description 感知范围 */
            perception?: components["schemas"]["PerceptionSchema"] | null;
            /**
             * Attributes
             * @description 属性模板定义
             */
            attributes: {
                [key: string]: components["schemas"]["AttributeSchema"];
            };
            /**
             * Actions
             * @description 该实体类型允许使用的动作列表
             */
            actions: string[];
        };
        /**
         * EnvironmentChange
         * @description 单个环境变量在整个仿真过程中的取值序列。
         *
         *     只收录"值发生变化"的 tick（含初始 tick）——未变化的 tick 省略，
         *     避免无意义膨胀。举例：若 `market_demand` 整个仿真保持 100 不变，
         *     `values` 只有一条 `(tick=0, value=100)`。
         */
        EnvironmentChange: {
            /**
             * Variable
             * @description 环境变量名
             */
            variable: string;
            /**
             * Values
             * @description 按 tick 升序的取值序列；只收录值变化过的 tick
             */
            values?: components["schemas"]["TickValuePoint"][];
        };
        /**
         * EnvironmentSchema
         * @description 环境变量模板集合。
         */
        EnvironmentSchema: {
            /**
             * Variables
             * @description 环境变量定义
             */
            variables: {
                [key: string]: components["schemas"]["AttributeSchema"];
            };
        };
        /**
         * EventListResponse
         * @description 事件查询的响应——含分页元信息。
         */
        EventListResponse: {
            /**
             * Events
             * @description EventRecord 列表（按发生顺序）；元素结构对齐 models.runtime_models.EventRecord
             */
            events?: unknown[];
            /**
             * Total
             * @description 过滤后命中的总条数（不分页）
             */
            total: number;
            /**
             * Has More
             * @description 是否还有下一页
             */
            has_more: boolean;
        };
        /**
         * EventRecord
         * @description append-only 事件轨迹中的一条记录。
         *
         *     对应 `运行时与事件轨迹设计.md` 4.3 节与第十节示例结构。事件一旦写入便不再修改，
         *     任何状态演化都通过"追加新事件"而非"改写旧事件"来表达。
         *
         *     ``payload`` 字段形状因 ``kind`` 不同而不同，本模型不做 payload 结构校验，
         *     由 `core/events.py` 的 recorder 对具体 kind 负责封装。
         */
        EventRecord: {
            /**
             * Event Id
             * @description 全局唯一事件 id
             */
            event_id: string;
            /**
             * Tick
             * @description 事件发生时的 tick，0 表示初始化事件
             */
            tick: number;
            /**
             * Kind
             * @description 事件类型
             * @enum {string}
             */
            kind: "decision_proposed" | "decision_rejected" | "decision_retried" | "fallback_used" | "action_executed" | "message_emitted" | "relation_changed" | "environment_changed" | "scheduled_event_triggered" | "intervention_applied" | "breakpoint_triggered" | "snapshot_saved" | "entity_created" | "entity_destroyed" | "chained_action_triggered";
            /**
             * Actor Id
             * @description 事件主体实体 id；环境事件 / 快照事件 / 干预事件等可能为 None
             */
            actor_id?: string | null;
            /**
             * Payload
             * @description 事件载荷；形状由 kind 决定，本层不校验
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应（GET /api/v1/health）。
         */
        HealthResponse: {
            /**
             * Status
             * @description server 状态
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @description Polisim 版本号
             */
            version: string;
            /**
             * Active Runs
             * @description 活跃 run 数
             */
            active_runs: number;
        };
        /**
         * Intervention
         * @description 人工干预记录。
         *
         *     对齐 `需求分析.md` 8.3 节"人工干预三级"，以及 D-008 对 Runtime 步进式接口的要求
         *     （`Runtime.intervene(intervention)`）：
         *
         *     1. ``inject_message``——向某实体（或广播）注入一条消息，绕过正常动作产出路径
         *     2. ``force_action``——强制某实体在指定 tick 执行一个动作，覆盖其 LLM/规则决策
         *     3. ``override_attribute``——直接修改实体属性，绕过规则层
         *
         *     所有 Intervention 经 Runtime 处理后会**同时**写入一条
         *     ``EventRecord(kind='intervention_applied')``，确保 `需求分析.md` 8.3 要求的
         *     "所有干预必须可追溯"。Intervention 对象本身是**输入**（通常来自 CLI / UI），
         *     不是 Event Log 的直接条目。
         *
         *     字段约束由 `model_validator` 强制：
         *
         *     - ``inject_message`` 必须提供 ``message``；``target_actor=None`` 表示广播
         *     - ``force_action`` 必须提供 ``action`` 与 ``target_actor``
         *     - ``override_attribute`` 必须提供 ``attribute_changes`` 与 ``target_actor``
         */
        Intervention: {
            /**
             * Tick
             * @description 生效 tick；干预在该 tick 开始前应用
             */
            tick: number;
            /**
             * Kind
             * @description 干预类型，对应需求分析 8.3 的三级
             * @enum {string}
             */
            kind: "inject_message" | "force_action" | "override_attribute";
            /**
             * Target Actor
             * @description 目标实体 id；inject_message 可为 None（广播）；其余两类必需
             */
            target_actor?: string | null;
            /**
             * Message
             * @description inject_message 时使用；至少包含 message_type 与 payload
             */
            message?: {
                [key: string]: unknown;
            } | null;
            /**
             * Action
             * @description force_action 时使用；至少包含 action_type 与 params
             */
            action?: {
                [key: string]: unknown;
            } | null;
            /**
             * Attribute Changes
             * @description override_attribute 时使用；键为属性名，值为新值
             */
            attribute_changes?: {
                [key: string]: unknown;
            } | null;
            /**
             * Reason
             * @description 操作者的说明/理由；可选，用于审计追溯
             */
            reason?: string | null;
        };
        /**
         * KindStat
         * @description 按 `EventKind` 的计数条目。
         */
        KindStat: {
            /**
             * Kind
             * @description EventKind 字面量
             */
            kind: string;
            /**
             * Count
             * @description 该 kind 出现的事件总数
             */
            count: number;
        };
        /**
         * MessageEnvelope
         * @description 消息信封：代表一条"已发出或已投递"的消息实例。
         *
         *     设计要点（对应 `运行时与事件轨迹设计.md` 第五节消息时序）：
         *
         *     1. 消息在 tick T 被某动作产生 → ``tick_emitted = T``、``tick_delivered = None``
         *     2. 下一 tick 开始时 Runtime 投递到目标 mailbox → ``tick_delivered = T + 1``
         *     3. ``tick_delivered is None`` 表示消息还在 outbox，本 tick 内对其他实体不可见
         */
        MessageEnvelope: {
            /**
             * Tick Emitted
             * @description 消息被发出的 tick
             */
            tick_emitted: number;
            /**
             * Tick Delivered
             * @description 消息被投递到收件箱的 tick；None 表示仍在 outbox
             */
            tick_delivered?: number | null;
            /**
             * Message Type
             * @description 消息类型名，必须在 World Definition.message_types 中声明
             */
            message_type: string;
            /**
             * From Actor
             * @description 发送方实体 id；为 None 表示来自 scheduled_event 注入
             */
            from_actor?: string | null;
            /**
             * Payload
             * @description 消息载荷；字段形状由 World Definition.message_types 规定
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * MessagePayloadFieldSchema
         * @description 消息载荷字段定义。
         */
        MessagePayloadFieldSchema: {
            /**
             * Type
             * @description 消息字段类型
             * @enum {string}
             */
            type: "string" | "number" | "boolean";
        } & {
            [key: string]: unknown;
        };
        /**
         * MessageSummary
         * @description 单 tick 消息统计。
         *
         *     第一版只维护最粗粒度的两个计数，不保存完整消息轨迹（完整轨迹走 EventRecord）。
         *     对应 `运行时与事件轨迹设计.md` 第十一节示例。
         */
        MessageSummary: {
            /**
             * Emitted
             * @description 本 tick 产生的消息数
             * @default 0
             */
            emitted: number;
            /**
             * Delivered Next Tick
             * @description 将在下一 tick 被投递的消息数
             * @default 0
             */
            delivered_next_tick: number;
        };
        /**
         * MessageTypeSchema
         * @description 消息类型模板。
         */
        MessageTypeSchema: {
            /**
             * Description
             * @description 消息类型描述
             */
            description?: string | null;
            /**
             * Delivery
             * @description 消息路由方式
             * @enum {string}
             */
            delivery: "direct" | "broadcast" | "by_relation";
            /**
             * Payload
             * @description 消息载荷字段定义
             */
            payload?: {
                [key: string]: components["schemas"]["MessagePayloadFieldSchema"];
            } | null;
        };
        /**
         * PauseMode
         * @description 暂停策略。
         */
        PauseMode: {
            /**
             * Manual
             * @description 是否允许手动暂停
             * @default true
             */
            manual: boolean;
            /**
             * Every Tick
             * @description 是否每 tick 自动暂停
             * @default false
             */
            every_tick: boolean;
        };
        /**
         * PauseResumeResponse
         * @description pause / resume endpoint 的响应（D-017 第 3.2 节）。
         */
        PauseResumeResponse: {
            /**
             * Status
             * @description 操作后的状态
             * @enum {string}
             */
            status: "paused" | "running";
            /**
             * Tick
             * @description 当前 tick
             */
            tick: number;
        };
        /**
         * PerceptionSchema
         * @description 实体感知范围定义。
         */
        PerceptionSchema: {
            /**
             * Scope
             * @description 感知范围类型
             * @enum {string}
             */
            scope: "global" | "relation" | "attribute" | "custom";
            /**
             * Include Relations
             * @description 需要纳入感知的关系类型列表
             */
            include_relations?: string[] | null;
        };
        /**
         * RelationInstance
         * @description 关系实例。
         */
        RelationInstance: {
            /**
             * Type
             * @description 关系类型，必须在 World Definition 中声明
             */
            type: string;
            /**
             * Source
             * @description 源实体 id
             */
            source: string;
            /**
             * Target
             * @description 目标实体 id
             */
            target: string;
            /**
             * Value
             * @description 关系强度或值（可选）
             */
            value?: number | null;
        };
        /**
         * RelationRuntimeState
         * @description 单个关系在当前 tick 的运行时状态。
         */
        RelationRuntimeState: {
            /**
             * Type
             * @description 关系类型名
             */
            type: string;
            /**
             * Source
             * @description 源实体 id
             */
            source: string;
            /**
             * Target
             * @description 目标实体 id
             */
            target: string;
            /**
             * Value
             * @description 关系强度或值（可选）
             */
            value?: number | null;
        };
        /**
         * RelationTypeSchema
         * @description 关系类型模板。
         */
        RelationTypeSchema: {
            /**
             * Description
             * @description 关系描述
             */
            description?: string | null;
            /**
             * Directed
             * @description 是否有方向
             */
            directed: boolean;
            /**
             * Transient
             * @description 是否允许在运行时动态变化
             */
            transient: boolean;
        };
        /**
         * RunDetail
         * @description run 完整详情——单 run 视图使用（POST /runs / GET /runs/:id 返回）。
         *
         *     含完整 world + scenario + runtime_config——前端可用作"创建后立即展示"
         *     与"刷新页面恢复跑前阶段配置"的数据源。
         */
        RunDetail: {
            /** @description run 摘要 */
            summary: components["schemas"]["RunSummary"];
            /** @description 完整 World Definition */
            world: components["schemas"]["WorldDefinition"];
            /** @description 完整 Scenario（含 ui_layout） */
            scenario: components["schemas"]["Scenario"];
            /** @description 生效的 runtime 配置 */
            runtime_config: components["schemas"]["RuntimeConfig"];
        };
        /**
         * RunSummary
         * @description run 摘要信息——列表场景使用（GET /runs 返回）。
         *
         *     `RunDetail` 进一步携带完整 world / scenario 配置。
         */
        RunSummary: {
            /**
             * Run Id
             * @description run 唯一标识
             */
            run_id: string;
            /**
             * World Id
             * @description World Definition.id
             */
            world_id: string;
            /**
             * Scenario Id
             * @description Scenario.scenario.id
             */
            scenario_id: string;
            /**
             * Status
             * @description run 当前状态——active：在跑；paused：暂停；finished：达 total_ticks；archived：已 GC 出内存
             * @enum {string}
             */
            status: "active" | "paused" | "finished" | "archived";
            /**
             * Current Tick
             * @description 当前 tick（0 表示未开始）
             */
            current_tick: number;
            /**
             * Total Ticks
             * @description 本次仿真总轮次
             */
            total_ticks: number;
            /**
             * Created At
             * Format: date-time
             * @description run 创建时间（UTC）
             */
            created_at: string;
        };
        /**
         * RuntimeConfig
         * @description `config/runtime.yaml` 的顶层模型。
         *
         *     此处字段只涉及"如何运行"，不涉及"世界是什么"或"场景如何配置"。
         *     业务默认值（`conflict_resolution` / `max_messages_per_tick` /
         *     `action_effect_order` 等）属于 World Definition 的 `defaults` 段，
         *     与本文件职责无关。
         */
        RuntimeConfig: {
            /**
             * Version
             * @description 配置文件版本
             * @constant
             */
            version: "0.1";
            /**
             * Random Seed
             * @description 全局随机种子；None 表示不固定
             */
            random_seed?: number | null;
            /**
             * Max Concurrent Decisions
             * @description 单 tick 内并行采集决策的并发数；第一版保守为 1
             * @default 1
             */
            max_concurrent_decisions: number;
            /**
             * Llm Request Timeout Sec
             * @description LLM 请求的整体超时秒数；与 LLMProviderConfig.timeout_sec 叠加（取较小值）
             * @default 30
             */
            llm_request_timeout_sec: number;
            /**
             * Output Language
             * @description LLM 输出自然语言字段时使用的语言（ISO 639-1 或自然语言名；LLM 会自行理解）。影响范围：决策层的 reason 字段、Phase C 分析层的叙事/判断/建议段落。**不**影响 JSON 结构字段（action / params 等）——那些是机器标识符，与语言无关。通过 prompt 注入生效，provider 层不关心。默认 zh-CN（简体中文）。
             * @default zh-CN
             */
            output_language: string;
            /**
             * Prompt History Size
             * @description D-016：build_prompt_context 在 actor_view.recent_decisions 中为 LLM 注入最近 N 条决策（按 tick 降序的 decision_proposed 事件）。上限 10——防 prompt context 爆炸；下限 0——完全关闭历史注入（恢复 D-016 第 1-2 步的「无记忆」行为）。默认 3——单 tick 不至于让 LLM 失忆，又不至于让历史段挤占 LLM 推理 token。
             * @default 3
             */
            prompt_history_size: number;
            /**
             * Max Chain Depth
             * @description D-015 全量版（session 28）：单 tick 内 ChainedActionEffect 链的**最大深度**。深度 = 同 tick 内一条原始动作产生的 chained 效果递归应用次数。链超此上限时 Runtime 抛 `RulesError` 防止无限递归（典型场景：rules 写错让 A → B → A 循环触发）。上限 20——足够覆盖任何合理规则链；下限 1——完全关闭同 tick 链（仍允许 delay_ticks>0 的跨 tick 链，跨 tick 链不计入此深度）。默认 3——足够大多数场景的合理链长。
             * @default 3
             */
            max_chain_depth: number;
        };
        /**
         * Scenario
         * @description 场景顶层模型。
         *
         *     这是一次具体仿真实例在 Python 中的结构化表示。
         *     它描述"本次仿真里具体是什么"，不描述世界的静态结构，
         *     也不定义动作如何生效。
         */
        Scenario: {
            /**
             * Version
             * @description 场景文件格式版本
             * @constant
             */
            version: "0.1";
            /**
             * World Id
             * @description 引用的世界定义 id
             */
            world_id: string;
            /**
             * Rules Module
             * @description 可选；规则模块导入路径（D-010），格式 'module.path:ClassName'。由 `core/rules_loader.load_rules_class` 解析为 `BaseRules` 子类。未声明时，Runtime 需由调用方显式传入 rules 实例。注：pattern 与 `schemas/scenario.schema.json` 保持同步。
             */
            rules_module?: string | null;
            /**
             * Ui Layout
             * @description v0.2 前端跑中主区 layout 风格选择（D-017 反向校验产物）。entity_card：实体卡片为主（minimal_market 默认）；relation_graph：力导向关系图为主（three_party_negotiation 默认）；event_stream：事件流瀑布为主（教学/阅读）。未显式声明时按 entity_card 处理。注：枚举值与 `schemas/scenario.schema.json` 保持同步。详见 `docs/02-design/v0.2-前端-UI-mockup.md` 第 7 节。
             * @default entity_card
             * @enum {string}
             */
            ui_layout: "entity_card" | "relation_graph" | "event_stream";
            /** @description 场景元信息 */
            scenario: components["schemas"]["ScenarioInfo"];
            /**
             * Entities
             * @description 实体实例列表，至少包含一个（D-003）
             */
            entities: components["schemas"]["EntityInstance"][];
            /**
             * Relations
             * @description 初始关系列表；未提供则为空（D-001）
             */
            relations?: components["schemas"]["RelationInstance"][];
            /**
             * Environment
             * @description 环境初始值；未提供的变量由 loader 回填 World Definition 默认值
             */
            environment?: {
                [key: string]: unknown;
            };
            /**
             * Scheduled Events
             * @description 预设事件列表；未提供则为空（D-001）
             */
            scheduled_events?: components["schemas"]["ScheduledEvent"][];
            /**
             * Breakpoints
             * @description 断点列表；未提供则为空（D-001）
             */
            breakpoints?: components["schemas"]["Breakpoint"][];
            /** @description 场景运行参数 */
            config: components["schemas"]["ScenarioConfig"];
        };
        /**
         * ScenarioConfig
         * @description 场景运行参数。
         */
        ScenarioConfig: {
            /**
             * Total Ticks
             * @description 本次仿真的总轮次
             */
            total_ticks: number;
            /**
             * Max Ticks
             * @description 安全上限；scenario_loader 需校验 `max_ticks >= total_ticks`
             */
            max_ticks?: number | null;
            /** @description 暂停策略（可选） */
            pause_mode?: components["schemas"]["PauseMode"] | null;
            /**
             * Snapshot Mode
             * @description 快照保存频率（可选）
             */
            snapshot_mode?: ("every_tick" | "on_pause" | "on_end") | null;
            /** @description 分析配置（可选） */
            analysis?: components["schemas"]["AnalysisConfig"] | null;
        };
        /**
         * ScenarioInfo
         * @description 场景元信息。
         */
        ScenarioInfo: {
            /**
             * Id
             * @description 场景唯一标识
             */
            id: string;
            /**
             * Name
             * @description 场景名称
             */
            name: string;
            /**
             * Description
             * @description 场景描述（可选）
             */
            description?: string | null;
        };
        /**
         * ScenarioSummary
         * @description 场景画廊卡片数据源（GET /api/v1/scenarios）。
         *
         *     D-017 反向校验产物：`ui_layout` 字段直接透传 `Scenario.ui_layout`——
         *     前端依据它选 entity_card / relation_graph / event_stream 三种主区 layout。
         */
        ScenarioSummary: {
            /**
             * Path
             * @description scenario.yaml 仓库相对路径
             */
            path: string;
            /**
             * Id
             * @description Scenario.scenario.id
             */
            id: string;
            /**
             * Name
             * @description Scenario.scenario.name
             */
            name: string;
            /**
             * Description
             * @description Scenario.scenario.description
             * @default
             */
            description: string;
            /**
             * Total Ticks
             * @description Scenario.config.total_ticks
             */
            total_ticks: number;
            /**
             * Ui Layout
             * @description v0.2 前端跑中主区 layout 风格选择（D-017 反向校验产物，详见 v0.2-前端-UI-mockup.md 第 7 节）
             * @default entity_card
             * @enum {string}
             */
            ui_layout: "entity_card" | "relation_graph" | "event_stream";
            /**
             * World Id
             * @description Scenario.world_id（前端可对齐 world 信息）
             */
            world_id: string;
        };
        /**
         * ScheduledEvent
         * @description 预设事件。
         *
         *     根据 `type` 的不同，`payload` 或 `message` 二者应至少一个被使用：
         *
         *     - `environment_event` → 使用 `payload` 描述环境变化
         *     - `message_injection` → 使用 `message` 描述注入的消息
         */
        ScheduledEvent: {
            /**
             * Tick
             * @description 触发 tick，最小值 1
             */
            tick: number;
            /**
             * Type
             * @description 事件类型
             * @enum {string}
             */
            type: "environment_event" | "message_injection";
            /**
             * Name
             * @description 事件名称（可选）
             */
            name?: string | null;
            /**
             * Payload
             * @description 事件载荷；`environment_event` 时使用
             */
            payload?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description 注入的消息内容；`message_injection` 时使用
             */
            message?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Snapshot
         * @description 某个 tick 结束后的全局快照。
         *
         *     对应 `运行时与事件轨迹设计.md` 4.4 节与第十一节示例。快照是**分析层**
         *     的主要输入源之一，要求能从任意一份快照 + 事件轨迹复原该 tick 的全貌。
         *
         *     - ``tick = 0`` 对应"场景加载完成、第 1 tick 开始前"的初始快照
         *     - 保存频率由 ``Scenario.config.snapshot_mode`` 决定，Runtime 按配置触发
         */
        Snapshot: {
            /**
             * Tick
             * @description 快照对应的 tick
             */
            tick: number;
            /**
             * Entity State Summary
             * @description 按实体 id 映射到属性快照（通常是当前 attributes 的拷贝）
             */
            entity_state_summary?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Relation State Summary
             * @description 当前关系状态列表，每项至少包含 type / source / target
             */
            relation_state_summary?: {
                [key: string]: unknown;
            }[];
            /**
             * Environment State
             * @description 环境变量快照
             */
            environment_state?: {
                [key: string]: unknown;
            };
            /** @description 消息统计（emitted / delivered_next_tick） */
            message_summary?: components["schemas"]["MessageSummary"];
        };
        /**
         * SnapshotsListResponse
         * @description 已保存的快照 tick 列表（GET /runs/:id/snapshots）。
         */
        SnapshotsListResponse: {
            /**
             * Ticks
             * @description 存在快照的 tick 编号列表（升序）
             */
            ticks?: number[];
        };
        /**
         * TickResult
         * @description 单次 tick 执行结果。
         *
         *     对应 `运行时与事件轨迹设计.md` 13.2 节约定——每次 `Runtime.step()` 返回
         *     一个本对象，包含：
         *
         *     - 本 tick 产生的**新增**事件列表（Runtime 已将它们 append 到 EventLog）
         *     - 本 tick 结束后的快照（``snapshot_mode`` 决定是否保存；未保存时为 None）
         *     - 本 tick 结束时是否应当暂停（``paused_after``）与触发的断点 id 列表
         *     - 是否达到 ``total_ticks`` 边界（``reached_total_ticks``）
         *
         *     **调用方契约**：
         *
         *     - ``events`` 是本 tick 新产生的记录——已经被 Runtime append 到 EventLog；
         *       TickResult 内的拷贝只是方便调用方同步消费（如 UI 实时刷新）
         *     - ``snapshot`` 为 None 表示本 tick 按 ``snapshot_mode`` 未保存，可通过
         *       `Runtime.get_snapshot(tick)` 随时补查（若运行时仍在内存中）
         *     - ``reached_total_ticks=True`` 时**不得**再调用 `step()`——Runtime 会拒绝
         */
        TickResult: {
            /**
             * Tick
             * @description 本次 step 完成后的 tick（从 1 起）
             */
            tick: number;
            /**
             * Events
             * @description 本 tick 产生的事件记录；可能为空
             */
            events?: components["schemas"]["EventRecord"][];
            /** @description 本 tick 结束后的快照；按 snapshot_mode 决定是否存在 */
            snapshot?: components["schemas"]["Snapshot"] | null;
            /**
             * Paused After
             * @description 本 tick 结束后是否应进入 paused 状态（每轮暂停 / 断点命中 / 手动 pause）
             * @default false
             */
            paused_after: boolean;
            /**
             * Triggered Breakpoints
             * @description 本 tick 命中的断点 id 列表（可能为空）
             */
            triggered_breakpoints?: string[];
            /**
             * Reached Total Ticks
             * @description 本 tick 是否已到 scenario.config.total_ticks——到达后不应再 step
             * @default false
             */
            reached_total_ticks: boolean;
        };
        /**
         * TickValuePoint
         * @description `(tick, value)` 对——某变量在某 tick 的取值。
         */
        TickValuePoint: {
            /**
             * Tick
             * @description tick；0 表示初始态
             */
            tick: number;
            /**
             * Value
             * @description 该 tick 的变量值
             */
            value: unknown;
        };
        /**
         * TrajectorySummary
         * @description 整次仿真的事件与节奏总览——对应 MVP 10.3 #1"全轨迹总结"。
         */
        TrajectorySummary: {
            /**
             * Total Ticks
             * @description 整个仿真实际推进的 tick 数（= 事件中的最大 tick）
             */
            total_ticks: number;
            /**
             * Total Events
             * @description events.jsonl 中的事件总数
             */
            total_events: number;
            /**
             * Events By Kind
             * @description 按 kind 分组的计数；按 kind 字典序排序
             */
            events_by_kind?: components["schemas"]["KindStat"][];
            /**
             * Events By Actor
             * @description 按实体 id 分组的行为计数；按 actor_id 字典序排序
             */
            events_by_actor?: components["schemas"]["ActorStat"][];
            /**
             * Paused Ticks
             * @description 触发了 breakpoint_triggered 事件的 tick 集合（升序去重）
             */
            paused_ticks?: number[];
            /**
             * Breakpoints Triggered
             * @description 命中的 breakpoint id 列表（按事件顺序，可能重复）
             */
            breakpoints_triggered?: string[];
        };
        /**
         * TurningPoint
         * @description tick-by-tick 扫描发现的显著属性变化。
         *
         *     定义：对于每对相邻快照 `snap_{t-1}` 与 `snap_t`，对每个实体的每个属性，
         *     若值发生变化，记作一条候选；按 `|delta|` 降序取前 K 条作为 turning points。
         *
         *     - `delta` 为 None：属性是非数值型（或 before/after 有一方非数值），
         *       无法计算差值；仍可能被保留为 turning point（按 0 排序，排在数值型之后）
         *     - `actor_id` 借用 `actor` 语义：指**实体 id**，不是事件发起者
         */
        TurningPoint: {
            /**
             * Tick
             * @description 属性变化发生的 tick（≥1；tick 0 是初始态）
             */
            tick: number;
            /**
             * Actor Id
             * @description 发生变化的实体 id
             */
            actor_id: string;
            /**
             * Attribute
             * @description 变化的属性名
             */
            attribute: string;
            /**
             * Before
             * @description 变化前的值
             */
            before?: unknown;
            /**
             * After
             * @description 变化后的值
             */
            after: unknown;
            /**
             * Delta
             * @description 数值差（after - before）；非数值属性为 None
             */
            delta?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorldDefinition
         * @description 世界定义顶层模型。
         *
         *     这是整个世界定义文件在 Python 中的结构化表示。
         *     它只描述静态结构，不描述一次具体仿真。
         */
        WorldDefinition: {
            /**
             * Version
             * @description 世界定义格式版本
             * @constant
             */
            version: "0.1";
            /** @description 世界元信息 */
            world: components["schemas"]["WorldInfo"];
            /**
             * Entity Types
             * @description 实体类型定义
             */
            entity_types: {
                [key: string]: components["schemas"]["EntityTypeSchema"];
            };
            /**
             * Relation Types
             * @description 关系类型定义
             */
            relation_types?: {
                [key: string]: components["schemas"]["RelationTypeSchema"];
            } | null;
            /**
             * Message Types
             * @description 消息类型定义
             */
            message_types?: {
                [key: string]: components["schemas"]["MessageTypeSchema"];
            } | null;
            /**
             * Action Types
             * @description 动作类型定义
             */
            action_types: {
                [key: string]: components["schemas"]["ActionTypeSchema"];
            };
            /** @description 环境变量模板 */
            environment?: components["schemas"]["EnvironmentSchema"] | null;
            /** @description 运行默认参数 */
            defaults?: components["schemas"]["DefaultsSchema"] | null;
        };
        /**
         * WorldInfo
         * @description 世界定义本身的元信息。
         */
        WorldInfo: {
            /**
             * Id
             * @description 世界唯一标识
             */
            id: string;
            /**
             * Name
             * @description 世界名称
             */
            name: string;
            /**
             * Description
             * @description 世界描述（可选）
             */
            description?: string | null;
        };
        /**
         * WorldState
         * @description 运行时世界状态聚合对象。
         *
         *     对应 `运行时与事件轨迹设计.md` 4.1 节。每个 tick 结束后，Runtime 应该持有
         *     一份"该 tick 结束时刻"的完整 WorldState，供下一 tick 的决策基础以及
         *     快照生成使用。
         *
         *     - ``tick = 0`` 代表"初始化完毕、尚未推进第 1 个 tick"的状态
         *     - ``tick = N (N >= 1)`` 代表"第 N 个 tick 执行完毕后的状态"
         */
        WorldState: {
            /**
             * Tick
             * @description 当前 tick，0 表示初始状态
             */
            tick: number;
            /**
             * Entities
             * @description 按实体 id 索引的当前状态字典
             */
            entities?: {
                [key: string]: components["schemas"]["EntityRuntimeState"];
            };
            /**
             * Relations
             * @description 当前生效的全部关系
             */
            relations?: components["schemas"]["RelationRuntimeState"][];
            /**
             * Environment
             * @description 当前环境变量值集合
             */
            environment?: {
                [key: string]: unknown;
            };
            /**
             * Mailboxes
             * @description 按实体 id 索引的收件箱；未出现的实体视为空收件箱
             */
            mailboxes?: {
                [key: string]: components["schemas"]["MessageEnvelope"][];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                /** @description 过滤 status：all / active / paused / finished / archived */
                status?: string;
                /** @description 分页大小 */
                limit?: number;
                /** @description 分页偏移 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_v1_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_run_api_v1_runs__run_id__step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_api_v1_runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_v1_runs__run_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_runs__run_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_v1_runs__run_id__snapshots__tick__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                tick: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description 精确匹配某 tick */
                tick?: number | null;
                /** @description 按 EventKind 过滤 */
                kind?: string | null;
                /** @description 按 actor_id 过滤 */
                actor_id?: string | null;
                limit?: number;
                offset?: number;
                /** @description 返 tick<=until_tick 的事件 */
                until_tick?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intervene_api_v1_runs__run_id__intervene_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Intervention"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_runs__run_id__analysis_get: {
        parameters: {
            query?: {
                /** @description 是否触发 Phase C LLM 增强 */
                enhance?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_analyze_api_v1_runs__run_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
